### ISSUE TITLE
Error: /usr/bin/python: can't find '__main__' module in 'odp2md'

### ISSUE THREAD

**Issue by 9s-l-s9** [seichter/odp2md#1]
Hello,

I get the stated error trying to execute the command `python odp2md --input examples/simple/simple-000.odp `

On my local machine and on google colab, Is this even the right way to execute the script?

**Comment by seichter** [comment]
Thanks for reporting. If you are running from code you might use 

```
python odp2md/__init__.py --input examples/simple/simple-001.odp -m
```
Flags -m (Markdown) or -x (eXtract media) are required. There are basicaily two issues with the script here: 1) packaging 2) command line interface is sub-optimal and should warn about the missing flag.

**Comment by seichter** [comment]
Packaging problem solved. CLI problem is handled in #2
